baseURL = 'https://blog.michaelkelly.org/'
languageCode = 'en-us'
title = 'Halting Problem 5.0'
theme = 'etch'

[author]
  name = "Michael Kelly"
  email = "m@michaelkelly.org"

[params]
  description = "A conspiracy of Cartographers"
  copyright = "Copyright © 2023 Michael Kelly."
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Blog homepage"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "mkorg"
    name = "michaelkelly.org"
    title = "My personal homepage"
    url = "https://www.michaelkelly.org"
    weight = 20

[permalinks]
  posts = '/:year/:month/:title/'
