baseURL = 'https://blog.michaelkelly.org/'
languageCode = 'en-US'
title = 'blog.michaelkelly.org'
theme = 'etch'

[params]
  description = "A conspiracy of Cartographers"
  copyright = "Copyright © 2023 Michael Kelly."
  dark = "auto"
  highlight = true
  favicon_name = "mk-favico.png"
  [params.author]
    email = 'm@michaelkelly.org'
    name = 'Michael Kelly'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Homepage for this blog"
    url = "/"
    weight = 10
    pre = "["
    post = "]"

  [[menu.main]]
    identifier = "mkorg"
    name = "michaelkelly.org"
    title = "My personal homepage"
    url = "https://www.michaelkelly.org"
    weight = 20
    pre = "["
    post = "]"

[permalinks]
  posts = '/:year/:month/:title/'

[outputs]
  home = ['html', 'rss']

